proxy:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/nginx_config:/etc/nginx
    - ${NFS_HOST}/nfs/nginx_releasenote:/usr/share/nginx/html

ldap:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/ldap_db:/var/lib/ldap
    - ${NFS_HOST}/nfs/ldap_static:/etc/ldap

jenkins:
  user: root 
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/jenkins_home:/var/jenkins_home 

registry:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/registry_certs:/certs
    - ${NFS_HOST}/nfs/registry_data:/data
