proxy:
  volumes:
    - nginx_config:/etc/nginx
    - nginx_releasenote:/usr/share/nginx/html

ldap:
  volumes:
      - ldap_db:/var/lib/ldap
      - ldap_static:/etc/ldap

jenkins:
  user: root 
  volumes:
    - jenkins_home:/var/jenkins_home 
    - /var/run/docker.sock:/var/run/docker.sock

registry:
  volumes:
    - registry_certs:/certs
    - registry_data:/data
